name: NuGet Release

on:
  push:
    tags: v*
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Build Version
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:11})" >> $GITHUB_ENV
    - name: Build
      run: dotnet build --configuration Release -p:Version=$RELEASE_VERSION
    - name: Test
      run: dotnet test --no-build --configuration Release --logger trx
    - name: Pack
      run: dotnet pack --no-build --output ./artifacts --configuration Release -p:Version=$RELEASE_VERSION
    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: ./artifacts
  publish-nuget:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    needs: [ build ]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      NUGET_AUTH_TOKEN: ${{ secrets.NUGET_APIKEY }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
        source-url: https://api.nuget.org/v3/index.json
    - uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
    - name: Upload to NuGet
      run:  dotnet nuget push ./artifacts/**/*.nupkg --skip-duplicate -n true -k $NUGET_AUTH_TOKEN
